FROM intel-npu-driver 
ENV DEBIAN_FRONTEND noninteractive
ENV TZ=america/los_angeles

RUN apt update && \
    apt install --no-install-recommends -q -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip

RUN mkdir /workspace && \
  cd /workspace && \
  pip3 install "intel-npu-acceleration-library @ git+https://github.com/intel/intel-npu-acceleration-library.git" && \
  pip3 install torchvision
